"""add pickup coordinates

Revision ID: f1f77579d372
Revises: 5be7841f59d1
Create Date: 2026-08-30 18:03:52.823794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1f77579d372'
down_revision: Union[str, Sequence[str], None] = '5be7841f59d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('pickup_latitude', sa.Float(), nullable=False))
    op.add_column('rides', sa.Column('pickup_longitude', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rides', 'pickup_longitude')
    op.drop_column('rides', 'pickup_latitude')
    # ### end Alembic commands ###
